### ISSUE TITLE
BottomSheet: разработать компонент

### ISSUE THREAD

**Issue by axin** [consta-design-system/uikit#2381]
Привет!

Адаптивная версия DatePicker-а на мокапах находится в контейнере, похожем на [Bottom Sheet](https://material.io/develop/android/components/bottom-sheet-dialog-fragment) из Material UI. Предлагаю вынести этот контейнер в отдельный компонент BottomSheet. Он будет очень полезен для адаптивного дизайна.

![Screenshot from 2022-06-09 22-15-49](https://user-images.githubusercontent.com/916893/172882511-736cf5c2-7d1d-4d8c-a350-d1e65477e45f.png)

**Comment by gizeasy** [comment]
- [ ] Берем Sidebar и доработаем до BottomSheet
- [ ] доработать описание Sidebar
- [ ] пример в фигму
- [ ] пример на портал
- [ ] прописать ключевые слова

**Comment by lisaovcharenko** [comment]
@gizeasy проверь, плиз, на актуальность

**Comment by lisaovcharenko** [comment]
Будет реализовано в рамках https://github.com/consta-design-system/uikit/issues/2212
