### ISSUE TITLE
doc: Как использовать для каждого компонента

### ISSUE THREAD

**Issue by arhayka** [consta-design-system/uikit#2761]
В документации компонентов, где есть примеры использования, сделать вкладку **Как использовать** и вынести туда все примеры. Например, в `Button`.

1. Вынести всё из обзора.
2. Проверить описание для разработчиков и вынести оттуда рекомендации по использованию тоже.

Пока тексты собираются здесь: https://www.figma.com/file/GHfK2MTZYaGpSxT7Imv0gM/Consta%3A-%D0%A0%D0%B5%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB%D0%B0?node-id=103%3A5937&t=tXvB6MXFF1RQHMEj-1

**Comment by gizeasy** [comment]
делать вместе с #2853

**Comment by BagenovA** [comment]
Таблица компонентов по библиотеке UI kit: https://docs.google.com/spreadsheets/d/1GUxTcaNQj-1sCn-7MU9jVd8KznuB3Bh_OeAme56axFw/edit?usp=sharing

**Comment by gizeasy** [comment]
план: 
1) отметь где надо или не надо
2) проставить приоритеты
3) начинаем писать доку

**Comment by gizeasy** [comment]
https://github.com/consta-design-system/uikit/issues/3021

**Comment by BagenovA** [comment]
@linturaven @hell0anna проставили в таблице приоритеты компонентов и определились с планом работы.

Примерный план работы:

1. Ресерч по проблемам, которые встречаются при работе с тем или иным компонентом (Леша, Аня)
2. Ресерч информации по компонентам и проблемам в других дизайн-системах и написание текста (Настя)
3. Ревью текста (Леша, Аня)
4. Определяемся с количеством собранной информации: если текста достаточно - делаем отдельную вкладку на странице компонента и ставим задачу на дизайн соответственно, если инфы мало - помещаем текст в Обзор без дизайна. (Настя, Леша, Аня)
5. Публикация результата работы на портале (Настя)

* Некоторым компонентам требуется доработка/пересборка (см. таблицу)

**Comment by BagenovA** [comment]
@linturaven @hell0anna следующий шаг: 

до 17 июля необходимо сделать ресерч по проблемам компонентов приоритета №1 и занести их в таблицу (https://docs.google.com/spreadsheets/d/1GUxTcaNQj-1sCn-7MU9jVd8KznuB3Bh_OeAme56axFw/edit?usp=sharing)

17 июля я выхожу из отпуска и приступаю к работе (на основе собранных проблем).

**Comment by BagenovA** [comment]
Как и договаривались на планировании, делим задачу на три блока по приоритетам компонентов. В комментарии выше уже описан план работы, я взяла его за основу и расписала шаги подробнее.

Чек-лист для блока №1:

- [ ] Провести опрос среди дизайнеров и контрибьютеров, чтобы узнать о проблемах в использовании компонентов (Настя)
- [ ] По результатам опроса выделить респондентов для интервью и назначить встречи (Аня, Леша)
- [ ] Провести интервью с респондентами, зафиксировать проблемы по компонентам 1 приоритета (и любых других, которые будут озвучены на интервью) в таблицу: https://docs.google.com/spreadsheets/d/1GUxTcaNQj-1sCn-7MU9jVd8KznuB3Bh_OeAme56axFw/edit?usp=sharing (Аня, Леша)
- [ ] Собранные материалы оформить в задачи на GitHub (если требуется доработка компонента) (Аня, Леша)
- [ ] Анализ информации и написание текста (Настя)
- [ ] Ревью текста (Леша, Аня)
- [ ] Определяемся с количеством собранной информации (Настя, Леша, Аня)
- [ ] Ставим задачу на создание дизайна, если нужно (Настя, Леша, Аня)
- [ ] Публикация результатов работы на портале (Настя)

**Comment by linturaven** [comment]
@alyonurchick1 

В ходе выполнения задачи нужно завести задачу под каждый компонент в формате [*номер эпика*] *Название компонента*: как использовать. Компоненты, которые требуют описания:
- [ ] AutoComplete
- [ ] AutoComplete (Multiple)
- [ ] Chips
- [ ] BookmarkTabs
- [ ] SnackBar
- [ ] Select
- [ ] Combobox
- [ ] List
- [ ] ContextMenu
- [ ] Tag

План действий:
- [ ] Изучить механику работы компонента
- [ ] Проконсультироваться с дизайнером на предмет частых ошибок в части использования
- [ ] Получить от дизайнера кейсы использования
- [ ] Сформировать описание для портала (можно частично использовать описание из Figma)
- [ ] Запросить у дизайнера макеты для примеров «правильно/не правильно» (если надо)
- [ ] Заполнить раздел на портале у конкретного компонента
- [ ] Передать PR на ревью дизайнеру
