### ISSUE TITLE
V5

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3207]
Обязательно:
- [x] https://github.com/consta-design-system/uikit/issues/3283
- [x] https://github.com/consta-design-system/uikit/issues/3139
- [x] https://github.com/consta-design-system/uikit/issues/3211
- [x] https://github.com/consta-design-system/uikit/issues/2896
- [x] https://github.com/consta-design-system/uikit/issues/2814
- [x] https://github.com/consta-design-system/uikit/issues/2658
- [x] https://github.com/consta-design-system/uikit/issues/3209
- [x] https://github.com/consta-design-system/uikit/issues/1818
- [x] https://github.com/consta-design-system/uikit/issues/3216

Если успеем:
- [x] https://github.com/consta-design-system/uikit/issues/2411
- [x] https://github.com/consta-design-system/uikit/issues/2271
- [x] https://github.com/consta-design-system/uikit/issues/2904
- [x] https://github.com/consta-design-system/uikit/issues/1416
- [x] https://github.com/consta-design-system/uikit/issues/3252

Релиз

- [x] Выкатываем beta v5
- [x] Обновляем все зависимые пакеты на v5 с поднятием мажерной версии
- [x] Правим баги если вылезут
- [x] Выкатываем стабильные пакеты (все)

**Comment by N1MBER** [comment]
Еще надо из TextField убрать свойство state, так как мы ему сделали аналог status но при переходе на 4 версию забыли убрать

**Comment by gizeasy** [comment]
> Еще надо из TextField убрать свойство state, так как мы ему сделали аналог status но при переходе на 4 версию забыли убрать
>  

Создай задачку и в список прикрепи
