### ISSUE TITLE
ConstaPortal: добавить кнопку перехода на опрос

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3319]
Хотим собирать обратную связь активнее, нужна кнопка перехода в инструмент для сбора обратной связи.

**Comment by lisaovcharenko** [comment]
По итогам обсуждения задачи с опросами записал:

- [ ] Размер: модальное окно или небольшое всплывающее окно
    - [ ] Интерфейс может быть любой
- [ ] Типы опросов
    - [ ] Сначала CSI, потом всё остальное
- [ ] Типы вопросов
    - [ ] Будем смотреть на количество и форму вопросов по ходу получения ответов в зависимости от качества
- [ ] Масштабирование на другие продукты
    - [ ] Будем масштабировать на другие продукты компании
- [ ] Триггер появления
    - [ ] Нет ограничений по триггерам
- [ ] Повторный запрос, когда и как
    - [ ] По очистке кэша или при заходе с другого устройства
- [ ] Как собираем данные (технические средства + ИБ)
    - [ ] МБ есть вариант прикрутить ЯндексМетрику, могут быть проблемы с ИБ
    - [ ] Хотелось бы СПА, но с их стороны проблемы по подгрузке данных
- [ ] Было бы оптимально опробовать опросы к концу ноября, провести АБ тест
- [ ] Планировали подотчётность в конце каждого портала, но этого недостаточно для объективной картины, поэтому хотим собирать постоянно. В перспективе может вырасти в другие вопросы. Из плюсов никого не надо пушить
- [ ] Гибридная механика — посмотреть на результаты тестов
- [ ] Периодичные всплывашки скорее не про CSI, а про что-то конкретное
- [ ] Узнать список сервисов для сбора данных (Лизе)
- [ ] Не можем добавлять скрипты из сторонних источников

**Comment by hell0anna** [comment]
возобновляем задачу

**Comment by linturaven** [comment]
@hell0anna @alyonurchick1 обсудить вопросы по опросу
