### ISSUE TITLE
Portal: Реструктуризация и редполитика

### ISSUE THREAD

**Issue by linturaven** [consta-design-system/uikit#3643]
**Хотим обновить структуру портала и сформировать редполитику.**

Обновление структуры будет состоять из двух частей:
1. Обновление структуры страниц по части контента
- [ ] Требования к описанию статьи
- [ ] Требования к описанию компонента

2. Обновление структуры портала (вложенность статей, библиотек, компонентов и т. д.) – **реализация станет возможна после перехода на монореп**

------------

Задачи по проработке редполитики:
- [ ] Сформулировать правила написания текста в компонентах
- [ ] Сформулировать правила наименования свойств компонентов

**Comment by gizeasy** [comment]
Мне нравиться когда дока идет по задачам от простых к сложным с примерами.
Сначала перечисляем простые свойства с примерами и описанием. Дальше показываем более сложные задачи где выше перечисленные свойства как-то комбинируются или разбавляются другими
