### ISSUE TITLE
Table: доработки на будущее

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3706]
- [x] #3807
- [ ] - переработать стиль ресайзера, сейчас есть проблема - при не зафиксированной шапке и многоуровневых ячейках не верно позиционируется ресайзер. Если сделать ресайдер только в шапке такой проблемы не будет. Договорились, убрать полоску увеличить область наведения оставляем смену курсора.
- [ ] - Вынести цвета элементов таблицы в отдельные переменные, таким образом дадим возможность семантически перекрашивать таблицу не меняя тему когда это необходимо. К примеру сделать фон прозрачным, или поменять цвет бордера.(Обсудить)
- [x] - Сделать рендер строки
- [x] - Пример с выделением строки, на ховер и на актив.
- [x] #3802
- [ ] - #3881 
- [x] - Создлать пример с закрепленной многоуровневой шапкой и столбцами одновременно, возможно добавить в стенд на главной.
- [x] #3803
- [x] #3804
- [ ] - В дизайне проработать наведение на строку. Взять цвета (control clear bg hover) этот цвет микестовать с цветом зебры.
- [x] #3805
- [x] #3806
- [ ] - Сделать гибкое управление разделителями. Вкл/Выкл горизонтальных и вертикальных по отдельности на всю таблицу.
- [ ] - Фиксация строк под шапкой, подумать
- [ ] - Сворачивание столбцев
- [ ] - Пустая табица
- [ ] - Редактирование ячеек
- [ ] - Фильтрация + примеры
- [ ] - Сортировка + примеры
- [ ] - Скрытие колонок
- [ ] - Сворачивание колонок
- [ ] - разработать Компоненты для рендера ячейки
- [ ] - разработать Компонент Тулбар (настройка таблицы выше шапки)
- [ ] - разработать Пагинация + пример
- [ ] - разработать Компонент для сворачивания таблицы
- [ ] - Перетаскивание строк (кастомная сортировка) (вроде не mvp)
- [x] - разработать Нумерацию строк
- [ ] - разработать Сортировка столбцов и предоставить api
- [ ] - разработать скрытие столбцов и предоставить api
- [ ] - Управление с клавиатуры, выделение ячейки, копирование ячейки
- [ ] - Текст на главную гитхаба
- [ ] - Пример с обьединением столбцев в строке

**Comment by ZettZet** [comment]
В пунктах смешаны dev и docs? Просто переработка ресайзера и темизации выглядит как что-то в коде. Как мне кажется, надо разграничить и взять в работу по отдельности

**Comment by gizeasy** [comment]
@ZettZet, эта задача как эпик, записываю сюда все что вижу по новым таблицам, далее декомпозируем.
